### ISSUE TITLE
build fails on mac

### ISSUE THREAD

**Issue by pdvnl** [ahknight/hfsinspect#25]
on osx 10.116 I'm trying to build hfsinspect, because I need some insight while trying to recover a damaged disk.

I followed the instructions:
```
$ git clone https://github.com/ahknight/hfsinspect.git
$ cd hfsinspect
$ make
```

this fails:
```
src/volumes/corestorage.c:15:10: fatal error: 'crc32c/crc32c.h' file not found
#include "crc32c/crc32c.h"
          ^
1 error generated.
```

apparently, crc32c needs to be available in the src directory.

but the Makefile suggest crc32c and memdmp in vendors:
```
SOURCEDIR = src
VENDORDIR = vendor
SOURCES = $(shell find $(SOURCEDIR) -type f -name *.c)
SOURCES += $(wildcard $(VENDORDIR)/crc32c/*.c)
SOURCES += $(wildcard $(VENDORDIR)/memdmp/*.c)
HEADERS = $(shell find $(SOURCEDIR) -type f -name *.h)
HEADERS += $(wildcard $(VENDORDIR)/crc32c/*.h)
HEADERS += $(wildcard $(VENDORDIR)/memdmp/*.h)
```

so I put crc32c and memdmp in both src and vendors, and then I get a new error:
```
Compiling vendor/crc32c/crc32c.c
vendor/crc32c/crc32c.c:29:5: warning: implicit declaration of function 'asm' is invalid in C99 [-Wimplicit-function-declaration]
    asm("pushl %%ebx\n\t" /* save %ebx */
    ^
vendor/crc32c/crc32c.c:32:22: error: expected ')'
        "popl %%ebx" : "=a"(eax), [ebx] "=r"(ebx), "=c"(ecx), "=d"(edx) : "a" (functionInput)
                     ^
vendor/crc32c/crc32c.c:29:8: note: to match this '('
    asm("pushl %%ebx\n\t" /* save %ebx */
       ^
1 warning and 1 error generated.
```

can you help please?

**Comment by jief666** [comment]
Maybe you forgot to clone with the recursive option to get submodules ?

**Comment by pdvnl** [comment]
> On 2018-06-14, at 14:20, jief666 <notifications@github.com> wrote:
> 
> Maybe you forgot to clone with the recursive option to get submodules ?

didn't know that I had to ...

make & install work fine now.

thanks,
paul.

**Comment by jief666** [comment]
I just discovered that today, trying to compile osxfuse. Looks like a repo can reference anther repo.
You're welcome.

**Comment by pdvnl** [comment]
to my shame i see that i didn't answer to your suggestion.
git clone --recursive solved the problem.
